Bennett
angelotheman/printf pull request #9
Opened 2023-08-22 13:27 UTC by Benobbi

added the file for task 1, wanted to your thoughts on them before we merge with the main branch

2023-08-22 14:15 UTC, angelotheman commented on main.h
> +{
There's this ending `{`

2023-08-22 14:20 UTC, angelotheman commented on main files/0-main.c
We can't push this `main.c` file. It's only for testing

2023-08-22 14:21 UTC, angelotheman commented on main files/2-main.c
We can't push this as it's for testing only

2023-08-22 14:22 UTC, angelotheman requested changes
I've commented on those that needs the fixing. Kindly resolve and let's move on.

Cheers to 🍕

2023-08-22 14:23 UTC, angelotheman commented
Less I forget, kindly change the name of your helper functions so that it doesn't conflict

2023-08-22 23:12 UTC, Benobbi reviewed
keeping the main.c files in a subfolder keeps them from being checked. the checks are done in the root of the repo.

2023-08-22 23:30 UTC, Benobbi commented on main.h
> +{
removed the bracket at the end

2023-08-22 23:45 UTC, Benobbi reviewed
deleted the curly bracket at the end of the main.h file. for the main.c files it should be fine as long as they are not in the root of the repo, we can also delete them altogether.

2023-08-23 00:50 UTC, angelotheman approved these changes
I'm approving these but I would edit in the merge conflicts. Some of them are just test cases. We would separate them into folders of their own

2023-08-23 00:53 UTC, merged